# 添加本文件：By LvQS: 20190620
spring:
  datasource:
    name: batsoft
    url: jdbc:mysql://localhost:3306/batsoft
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    read-size: 2 #Added By LvQS: 20190620
  redis: # Added by: LvQS:20190620 TODO:待完善信息
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  cloud:
    config:
      profile:

shiro:
  session: # TODO：BY LvQS:20190620 配置完成
    global-session-timeout: 18000
  cookie: # TODO：BY LvQS:20190620 配置完成
    sessionIdCookie:
      name:

# TODO：BY LvQS:20190620 配置完成
# 应用配置
batsoft:
  name:
  validCode:
  mobileCode:
  emailCode:
  desc:
  file:
    basepath:
  static-assets:
  lucene:
    server:
  tplPath:
  defaultCoin:

# TODO：BY LvQS:20190620 配置完成
http:
  maxTotal: 2
  defaultMaxPerRoute: 20
  connectTimeout: 5000
  connectionRequestTimeout: 5000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true